name: spremanje_modular
description: Modularna arhitektura za spremanje profila
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  permission_handler: ^11.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  file_selector: ^1.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
